#!/usr/bin/env python3
"""Turn sweep_defaults.py's JSON into the table the paper needs.

The sweep answers one question -- does the MLP-over-LR gap depend on the arbitrary
defaults -- so the table reports, per run, the shipped cell and then the RANGE each
probe takes as one knob moves at a time. A range is the honest summary here: quoting
only the best cell would be selection on the test split, and quoting only the default
would be the very thing the sweep exists to check.

`best-of-grid` is each probe's best cell anywhere in the grid. Both numbers are
test-selected and neither is an honest estimate of that probe's accuracy; the
comparison BETWEEN them is what matters, because it is the strongest form of the
fairness check -- LR at its most flattering against the MLP at its most flattering.

  python filtering/sweep_table.py filtering/figures/sweep_defaults.json \
      filtering/figures/sweep_defaults_gemma3.json --out filtering/figures/paper/table_sweep.tex
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

AXES = [("topk", "top-$k$ heads"), ("C", "LR $C$"), ("hidden", "MLP width")]


def spans(rows, axis):
    cells = [r for r in rows if r["axis"] in (axis, "default")]
    lr = [r["lr_controlled"] for r in cells]
    mlp = [r["mlp_controlled"] for r in cells]
    gaps = [r["gap_controlled"] for r in cells]
    return min(lr), max(lr), min(mlp), max(mlp), min(gaps), max(gaps)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("json", nargs="+")
    ap.add_argument("--out", default="filtering/figures/paper/table_sweep.tex")
    args = ap.parse_args()

    runs = {}
    defaults = None
    for p in args.json:
        d = json.loads(Path(p).read_text())
        defaults = defaults or d["defaults"]
        runs.update(d["runs"])

    lines = [
        "% Auto-generated by filtering/sweep_table.py -- do not edit by hand.",
        "% Sensitivity of the controlled probes to the three arbitrary defaults, one",
        f"%   axis varied at a time around topk={defaults['topk']}, "
        f"C={defaults['C']}, hidden={tuple(defaults['hidden'])}.",
        "% Ranges are min-max over the cells on that axis (the default cell included).",
        "% 'best' is each probe's best cell ANYWHERE in the grid: both are selected on",
        "%   the test split, so neither is an honest accuracy estimate on its own. Their",
        "%   difference is the fairness check -- LR at its best against the MLP at its best.",
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"Run & Varying & LR-ctrl & MLP-ctrl & MLP $-$ LR \\",
        r"\midrule",
    ]
    for tag, r in runs.items():
        rows = r["rows"]
        dflt = next(x for x in rows if x["axis"] == "default")
        name = tag.replace("_", r"\_")
        lines.append(
            f"{name} & default & {dflt['lr_controlled']:.3f} & "
            f"{dflt['mlp_controlled']:.3f} & {dflt['gap_controlled']:+.3f} \\\\")
        for axis, label in AXES:
            lo_l, hi_l, lo_m, hi_m, lo_g, hi_g = spans(rows, axis)
            lines.append(
                f" & {label} & {lo_l:.3f}--{hi_l:.3f} & {lo_m:.3f}--{hi_m:.3f} & "
                f"{lo_g:+.3f}--{hi_g:+.3f} \\\\")
        b = r["best_of_grid"]
        lines.append(
            f" & \\emph{{best}} & {b['lr_controlled']:.3f} & {b['mlp_controlled']:.3f} "
            f"& {b['gap']:+.3f} \\\\")
        lines.append(r"\midrule")
    lines[-1] = r"\bottomrule"
    lines.append(r"\end{tabular}")

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines))
    print(f"\nwrote {out}")

    # Plain-language summary, so the claim in the text is read off the same numbers.
    print("\n--- summary ---")
    worst = min((r["best_of_grid"]["gap"], t) for t, r in runs.items())
    for tag, r in runs.items():
        rows = r["rows"]
        g = [x["gap_controlled"] for x in rows]
        print(f"  {tag:16s} gap over ALL {len(rows)} cells: "
              f"{min(g):+.3f} .. {max(g):+.3f}   best-of-grid {r['best_of_grid']['gap']:+.3f}")
    print(f"  MLP > LR in every cell of every run: "
          f"{all(x['gap_controlled'] > 0 for r in runs.values() for x in r['rows'])}")
    print(f"  smallest best-of-grid gap: {worst[0]:+.3f} ({worst[1]})")


if __name__ == "__main__":
    main()
